### ISSUE TITLE
Multi-object tracking?

### ISSUE THREAD

**Issue by lyuchuny3** [bertinetto/siamese-fc#10]
Thanks for you works. I'm interested if your code can be used for multi-object tracking at the same time? The demo videos provided are all single object tracking.

**Comment by bertinetto** [comment]
Hi,
At the moment the single (arbitrary) object tracking and the multi-target tracking communities are trying to solve different (albeit overlapping) problems and thus use different settings and benchmarks. Our papers and methods are focused on the former.

Although (as for most single tracking algorithms) with some effort you can use our work also for multi-object tracking.
You can do it naively, e.g. initalizing multiple instances of SiamFC or maybe more fancily, e.g. using a single instance with a larger search area and try to understand the multiple modes of the response.

In any case, you will have the problem of data association, but fortunately heaps of literature have been written on it.
