### ISSUE TITLE
Error during training step when running run_experiment(imdb_video)

### ISSUE THREAD

**Issue by Jumabek** [bertinetto/siamese-fc#12]
Hi @bertinetto  and other siamese-fc users,
I am trying to train the network by following the instructions.
However I get the following error when I ran run_experiment(imdb_video)

```
>> run_experiment(imdb_video.imdb_video);
construct network

ly = 

  struct with fields:

            type: 'conv'
            name: 'conv1'
         weights: {[11×11×3×96 single]  [96×1 single]}
          stride: 2
             pad: 0
    learningRate: [1 2]
     weightDecay: [1 0]
            opts: {'CudnnWorkspaceLimit'  [1.0737e+09]}

Reference to non-existent field 'dilate'.

Error in vl_simplenn_display (line 82)
      ks = (ks - 1) .* ly.dilate + 1 ;

Error in vid_create_net>add_block (line 60)
info = vl_simplenn_display(net) ;

Error in vid_create_net>modified_alexnet (line 141)
    net = add_block(net, opts, '2', 5, 5, 48, 256, strides(3), 0) ;

Error in vid_create_net (line 28)
    net = modified_alexnet(struct(), opts) ;

Error in make_siameseFC (line 22)
    branch = vid_create_net(...

Error in experiment>make_net (line 137)
    net = make_siameseFC(opts);

Error in experiment (line 69)
    net = make_net(opts);

Error in run_experiment (line 17)
	experiment(imdb_video, opts);
```

I understand error is raising because there is not dilate property in the layers. However, how to fix this?
Should I simply  change the line 82 in vl_simplenn_display to 
`ks = (ks - 1)  + 1 ;
`
by removing the dilate? Or does it has to do something with the version of MatConvNet that I am using?

Thanks,
Jumabek

**Comment by bertinetto** [comment]
Hi Jumabek,
Recent versions of MatConvNet require you to explicitly set the 'dilate' property when building the network.
Just make sure you have latest MatConvNet version and set it to [1 1] whenever you add a conv layer.

Hope this helps,
Luca

**Comment by Jumabek** [comment]
Thanks a lot Luca, that solved the issue. 
However, small change needed. I set `ly.dilate = [1;1];`
Otherwise, `ly.dilate = [1 1]` resulted `ks`  variable to become 4x4 array.
Hope this might help somebody else.
