### ISSUE TITLE
How about gaussian weights?

### ISSUE THREAD

**Issue by Jiangfeng-Xiong** [bertinetto/siamese-fc#20]
Different label weights strategy has been implemented in the code, however, intuitively, gaussian weights should work better, since we should emphasize on the center of the object, weight in the center should have a larger value. So, How about the performance of gaussian weights, @bertinetto.Has anyone tried this? Or have any ideas about why balanced weights work better than the gaussian weights?

**Comment by bertinetto** [comment]
Hi,
You are right and using gaussian weights is one of the things we tried.
Quite surprisingly though they didn't deliver better better results during training
We also tried to use ternary weights (i.e. positive, negative, neutral), again without improvements during training.

However, we never used this network for tracking, so there might be some untapped performance gain there.
