### ISSUE TITLE
about the pretrained .net.mat file

### ISSUE THREAD

**Issue by AnnaraMA** [bertinetto/siamese-fc#21]
Hi Luca,

is there any files can help to use the pretrained .mat file like '2016-08-17.net.mat' for training my own dataset?

thank you!

**Comment by bertinetto** [comment]
Hi and sorry for the late answer.
I am not sure to understand your question:
* The file you mention is a pretrained network you can use for the "tracking only" mode described in the README
* You can use it as a starting point and "fine tune" it for your purpose
