### ISSUE TITLE
Training on Negative Samples

### ISSUE THREAD

**Issue by suryaprakaz** [bertinetto/siamese-fc#23]
Hi! First of all, I wanna appreciate the great work you have done in object tracking!
Could you please clarify me on training the siamese network with negative samples? i.e. images from two different imagenet sequences
In your paper, you mention something like,

> We employ a discriminative approach, training the network on positive and
negative pairs and adopting the logistic loss

In line 178 of experiment.m, 
`    neg_eltwise = [];   % no negative pairs at the moment`
you specify that no negative pairs are used at the moment. 

Is there a reason why negative pairs were not included during training? Thanks in advance!

**Comment by bertinetto** [comment]
Hi! Thanks :)
We found out that using negative pairs doesn't actually affect the performance.
It's probably because the negative examples are not "hard enough".
