### ISSUE TITLE
how is the number of channels changed from 96 to 48 as input of conv2?

### ISSUE THREAD

**Issue by XHUJOY** [bertinetto/siamese-fc#24]
how is the number of channels changed from 96 to 48 as input of conv2?

The number of the feature channels of conv1 is 96. However after batchnorm, relu and pool layers, it changes to 48. This confuses me a lot. Which layer changes the number of channels?

**Comment by Jiangfeng-Xiong** [comment]
As I known, it is the same as Alexnet. If you know caffe, it means that we set group to 2 in Convolutional Layer.That is to say
> the first half of the filters are only connected to the first half of the input channels, and the second half only connected to the second half.

So,it's half of the original input channel num 96, (namely,48)
you can refer to this [issue](https://github.com/BVLC/caffe/issues/778) of caffe

**Comment by XHUJOY** [comment]
thx, i got it.
