### ISSUE TITLE
can the prototxt and caffemodel be provided?

### ISSUE THREAD

**Issue by cndylan** [bertinetto/siamese-fc#32]

**Comment by cndylan** [comment]
I want to make use of sianese-fc in a c++ platform.  can prototxt and caffemodel be provided ?

**Comment by ym547559398** [comment]
Have you implemented this on caffe? The process is complex.

**Comment by cndylan** [comment]
I have implemented this on caffe. hahha~

**Comment by ym547559398** [comment]
Wow,that's excellent! Will you release your code to make our learning process easier?

**Comment by cndylan** [comment]
Sorry, I have no permission to release the code because of some other reasons.
