### ISSUE TITLE
What is the meaning of "opts.instanceSize = 255 - 2*8" in line 19, experiment?

### ISSUE THREAD

**Issue by haichaoyu** [bertinetto/siamese-fc#35]
Why not just "opts.instanceSize = 239"? Thanks!

**Comment by jvlmdr** [comment]
We originally used instanceSize of 255 pixels. However, when we added translation augmentation, we extracted the center window with an 8-pixel margin on either side, to allow for the augmentation.

**Comment by haichaoyu** [comment]
@jvlmdr Thank you.
