### ISSUE TITLE
evaluation code

### ISSUE THREAD

**Issue by pribadihcr** [bertinetto/siamese-fc#4]
Hi @bertinetto 

Is there example code to measure the performance ?. thanks

**Comment by xpain1** [comment]
Hi @bertinetto  
What's the meanning of '/path/to/deep-one-shot/util'in startup.m?

**Comment by bertinetto** [comment]
It's a template/example path, you should fill in the absolute path of your
deep-one-shot/util folder

**Comment by xpain1** [comment]
Thanks,but I don't find a folder  named 'deep-one-shot'

**Comment by xpain1** [comment]
@bertinetto 
Thanks,but I don't find a folder named 'deep-one-shot'?

**Comment by bertinetto** [comment]
oh i see, that was the name of the private repo.
it's siamese-fc/util

**Comment by xpain1** [comment]
@bertinetto 
oh i see ,thanks!

**Comment by YgRen** [comment]
Hi，Where i can get your evaluation code in OTB and VOT，I want to reappear your results，Thanks.

**Comment by bertinetto** [comment]
Hi, I didn't commit the evaluation code but it should be straightforward.
Consider that I have used the network trained with 20% grayscale to the on
OTB (shared in the project page)
Otherwise, I have shared all computed bounding boxes on the project page
http://www.robots.ox.ac.uk/~luca/siamese-fc.html

Cheers,
Luca

**Comment by xpain1** [comment]
Hi, @bertinetto 
i met some trouble when i try to train the net .there is non-existent field named 'dilate' in the layer 'conv1',but you use it in the   info = vl_simplenn_display(net) ,so  i want to know the reason,thanks!
here is my error:
Reference to non-existent field 'dilate'.

Error in vl_simplenn_display (line 82)
      ks = (ks - 1) .* ly.dilate + 1 ;

Error in vid_create_net>add_block (line 60)
info = vl_simplenn_display(net) ;

Error in vid_create_net>modified_alexnet (line 141)
    net = add_block(net, opts, '2', 5, 5, 48, 256, strides(3), 0) ;

Error in vid_create_net (line 28)
    net = modified_alexnet(struct(), opts) ;

Error in make_siameseFC (line 22)
    branch = vid_create_net(...

Error in experiment>make_net (line 136)
    net = make_siameseFC(opts);

Error in experiment (line 69)
    net = make_net(opts);

Error in run_experiment (line 17)
	experiment(imdb_video, opts);

**Comment by xpain1** [comment]
hi @bertinetto 
 i know why that happened.because my matconvnet is 1.0-21,which has a dilate in the conv layer.so in the vl_simplenn_display,the error occured. i change my natconvnet from 1.0-21 to 1.0-20,the code is succeed.
