### ISSUE TITLE
Training result is not as well as the paper .

### ISSUE THREAD

**Issue by cndylan** [bertinetto/siamese-fc#42]
I trained the alexNet, But the result is a little lower than the paper said, about 0.02(success plot)!
In addition, How can I select gray training mode？

![Uploading image.png…]()

**Comment by bertinetto** [comment]
Hi,
It is unlikely that the results exactly match the paper when training from scratch. There are simply too many factors: cuda/cudnn/matconvnet versions, data preprocessing, ... It would be easier if we could have shared the exact dataset we used, but Imagenet license does not allow us to do so. 

In experiment.m, you can set opts.augment.grayscale to 1 and train a new version of the network specialized to grayscale.
