### ISSUE TITLE
Difference instanceSize when training and testing

### ISSUE THREAD

**Issue by zhangliliang** [bertinetto/siamese-fc#5]
Hi. Thanks for sharing such a good code for studying.

I have a problem when reading your code.

In the testing procedure, the instanceSize set to 255. However, during the training time the instanceSize is set to 255 - 2*8.

Why they are different? And what is the meaning of subtracting 2*8 during the training time?

Wait for your response.

**Comment by bertinetto** [comment]
Hi,
Yep, it's not explained in the comments, sorry for that.
Those 2*8 should be subtrated*only* when opts.augment.translate and/or opts.augment.stretch are true and they account for transformations that could potentially make a 255 patch overflow.

**Comment by zhangliliang** [comment]
Oh, I see.

Thanks for replying. :)
