### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by UCL-Abbas** [bertinetto/siamese-fc#50]
Hello,
Thanks for making this work public - just wanted to ask as to the broken links provided in the repository, can they be reset or maybe they have they been removed ?

Specifically I am talking about the links mentioned in this line:
"Run vid_setup_data.m to generate your own imdb_video.mat. Otherwise download the one we have already created - here for the one used for the ECCV'16 SiamFC, here for the one used for the CVPR'17 CFNet. 7bis. (only for CVPR'17 CFNet code) Add a field .set "

Thanks,
Abbas

**Comment by bertinetto** [comment]
Hi, Thanks for pointing this out!
All broken links should now be fixed :)
