### ISSUE TITLE
about disk size.

### ISSUE THREAD

**Issue by NeverMoreLCH** [bertinetto/siamese-fc#64]
Hi,
Your work is really great. I want to train the siamese-fc network, and I have download the 86GB dataset. I want to know that I need how much disk size if I train the network follow your paper ( include date augment, scale ... ). My disk only have about 200GB free space, I don't konw if it's enough.
Thanks.

**Comment by bertinetto** [comment]
Hi,
Thank you!
No, 200GB should be more than enough.
