### ISSUE TITLE
Why keep the original ratio of the object when generating the exemplar

### ISSUE THREAD

**Issue by zhangliliang** [bertinetto/siamese-fc#9]
Hi,

When generating the exemplar for the tracking object, the code try to add 50% background as the context information while keep the original ratio of the object. 

In my opinion, this strategy might be harmful especially when the tracking object ratio is very small or very big. (e.g. the pedestrians, whose ratios are around 0.4). In this situation, the strategy might involve too much background (might over 70% or more) into the exemplar. And then, the tracker might be pay more attention to the background instead of the tracking object, which might hurt the robustness of the tracker.

In my opinion, I prefer the brute-force strategy which is adopted in the R-CNN. It ignores the ratio of the object and just resizes the object to a fixed size, and then adds fixed size background as the context information. 

Could you kindly give some comments for comparing these two strategies?

**Comment by bertinetto** [comment]
Hi,
Sorry for the late answer.
That's a good point.
The data preprocessing/curation we came up with is actually the result of a single iteration and far from optimal :)
Resizing to fixed size like in R-CNN is surely an alternative, but it would as well penalize object with an unbalanced aspect ratio.
But thanks a lot for pointing this out, we will try it out.
Or please, if you try it yourself and notice significant difference (better/worse) please share :)

**Comment by zhangliliang** [comment]
Hi, thinks for your replying.

Actually I try to resize the exemplar in the R-CNN manner, and then try it on some videos which are collected by myself. It seems to be helpful in some scenarios.

For example, one situation is that the exemplar is a standing person who is surrounding by other persons. Then he walk out from the crowd and go to another place. 

The original resized method seems to involve too much background (e.g. other persons) into the exemplar. When the person moves, the tracking box still tends to stay at the original position, since it might be fitting to the background. 

The R-CNN-like resized method performs good tracking results in this video. It seems to be helpful in this situation.

**Comment by bertinetto** [comment]
Awesome!
It would be really helpful for us and the community (if you have some spare
time) to show some quantitative results on your videos or better on some
benchmark, e.g. OTB.
Thanks for the tip anyway.
